FROM bellsoft/liberica-openjdk-alpine
COPY ./java ./src
RUN mkdir ./out
RUN javac -sourcepath ./src -d java/ru/JavaCoreSimplePractice/PackOne/Main.java
CMD java -classpath ./out ru.JavaCoreSimplePractice.PackOne.Main 